[package]
name = "aquavm-air-cli"
version = "0.4.5"
edition = "2021"
description = "AIR execution and printing tool"
authors = ["Fluence Labs"]
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/aquavm-air-cli"
keywords = ["fluence", "air", "tracing"]

[dependencies]
aquavm-air = { version = "0.48.0", path = "../../../air" }
air-beautifier = { version = "0.3.1", path = "../../../crates/beautifier" }
avm-data-store = { version = "0.7.1", path = "../../../crates/data-store" }
avm-interface = { version = "0.29.1", path = "../../../avm/interface" }
air-interpreter-interface = { version = "0.15.1", path = "../../../crates/air-lib/interpreter-interface", default-features = false }
air-test-utils = { version = "0.10.4",path = "../../../crates/air-lib/test-utils", optional = true }

anyhow = "1.0.70"
clap = { version = "4.2.7", features = ["derive", "env"] }
itertools = "0.10.5"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.95"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", default-features = false, features = [ "env-filter", "json", "smallvec", "time", "fmt" ] }
atty = "0.2.14"
termcolor = "1.2.0"
fluence-keypair = "0.10.3"
bs58 = "0.5.0"
zeroize = "1.6.0"

# near
near-sdk = { version = "4.1.1", optional = true }
tokio = { version = "1", features = ["rt"], optional = true }
workspaces = { version = "0.7.0", optional = true }

[features]
default = ["wasm"]
wasm = ["air-test-utils"]
near = [ "dep:near-sdk", "dep:tokio", "dep:workspaces" ]

[[bin]]
name = "air"
path = "src/main.rs"
