[package]
name = "air-interpreter-signatures"
description = "AIR interpreter signatures util module"
version = "0.1.1"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
documentation = "https://docs.rs/air-interpreter-signatures"
repository = "https://github.com/fluencelabs/aquavm/tree/master/crates/air-lib/interpreter-signatures"
keywords = ["fluence", "air", "programming-language"]
categories = ["wasm"]

[dependencies]
air-interpreter-cid = { version = "0.3.0", path = "../interpreter-cid" }
fluence-keypair = { version = "0.10.3", default-features = false }

serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"

bs58 = "0.5.0"
