[package]
name = "air-trace-handler"
version = "0.5.3"
description = "Implementation of AIR trace handler"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_trace_handler"
path = "src/lib.rs"

[dependencies]
air-interpreter-cid = { version = "0.3.0", path = "../interpreter-cid" }
air-interpreter-data = { version = "0.11.3", path = "../interpreter-data" }
air-log-targets = { version = "0.1.0", path = "../log-targets" }
aquavm-air-parser = { version = "0.10.0", path = "../air-parser" }
polyplets = { version = "0.5.1", path = "../polyplets" }

bimap = "0.6.3"
serde_json = "1.0.95"
log = "0.4.17"
thiserror = "1.0.40"
tracing = "0.1.37"
num-traits = "0.2.16"
