[package]
name = "air-test-utils"
version = "0.10.4"
description = "Test utils for the AIR interpreter"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/air-test-utils"
keywords = ["fluence", "air", "webassembly", "security", "authorization"]
categories = ["wasm"]

[lib]
name = "air_test_utils"
path = "src/lib.rs"

[dependencies]
aquavm-air = { version = "0.48.0", path = "../../../air" }
air-interpreter-cid = { version = "0.3.0", path = "../interpreter-cid" }
air-interpreter-data = { version = "0.11.3", path = "../interpreter-data" }
air-interpreter-interface = { version = "0.15.1", path = "../interpreter-interface" }
avm-interface = { version = "0.29.1", path = "../../../avm/interface" }
avm-server = { version = "0.33.1", path = "../../../avm/server" }
marine-rs-sdk = "0.10.0"

object-pool = "0.5.4"
once_cell = "1.17.1"
semver = "1.0.17"
serde_json = "1.0.95"
serde = { version = "1.0.164", features = ["derive"] }
fluence-keypair = "0.10.3"

ed25519-dalek = "1.0.1"
rand_chacha = "0.2.2"
sha2 = "0.10.6"

[dev-dependencies]
maplit = "1.0.2"

[features]
test_with_native_code = []
