[package]
name = "air-lambda-parser"
description = "Parser of an AIR lambda"
version = "0.1.0"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/air-lambda-parser"
keywords = ["fluence", "air", "parser", "lalrpop"]
categories = ["wasm"]

[lib]
name = "air_lambda_parser"
path = "src/lib.rs"

[build-dependencies]
lalrpop = "0.20.0"

[dependencies]
air-lambda-ast = { version = "0.1.0", path = "../ast" }

lalrpop-util = "0.20.0"
regex = "1.9.5"

# TODO: hide serde behind a feature
serde = { version = "1.0.164", features = ["rc", "derive"] }

itertools = "0.10.5"
thiserror = "1.0.40"
