[package]
name = "air-interpreter-data"
description = "Data format of the AIR interpreter"
version = "0.11.3"
authors = ["Fluence Labs"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/aquavm"
documentation = "https://docs.rs/air-interpreter-data"
keywords = ["fluence", "air", "webassembly", "programming-language"]
categories = ["wasm"]

[lib]
name = "air_interpreter_data"
path = "src/lib.rs"

[dependencies]
air-utils = { version = "0.1.1", path = "../utils" }
aquavm-air-parser = { version = "0.10.0", path = "../air-parser" }
air-interpreter-cid = { version = "0.3.0", path = "../interpreter-cid" }
air-interpreter-signatures = { version = "0.1.1", path = "../interpreter-signatures" }
polyplets = { version = "0.5.1", path = "../polyplets" }

serde = {version = "1.0.164", features = ["derive", "rc"]}
serde_json = "1.0.95"
semver = { version = "1.0.17", features = ["serde"] }
once_cell = "1.17.1"
tracing = "0.1.37"
newtype_derive = "0.1.6"
num-traits = "0.2.16"
